monitor:
  image: iis-recover
  container_name: iis-recover
  net: host
  environment:
    - TZ=Asia/Shanghai
  volumes:
    - ./ansible_hosts:/etc/ansible/hosts
    - ./config.yml:/opt/app/src/config.yml
  restart: always