monitor:
  image: unknowname/monitor-auto
  container_name: monitor-auto
  net: host
  environment:
    - TZ=Asia/Shanghai
  volumes:
    - ./ansible_hosts:/etc/ansible/hosts
    - ./config.yml:/opt/app/src/config.yml
  restart: always