default:
  # 60秒内累计7次
  duration: 60
  timeout: 5
  max_failed: 5
  path: /
  # 自动干预间隔时间，防止恶性循环，同时用于通知发送的间隔时间
  auto_interval: 200
  max_inactive: 1
  recover: False
  check_interval: 1
  check_method: get

sites:
  - site: www.aaa.com
    # 具体怎么Recover不管，要具体实现一个AbstractRecoverAction
    recover:
      enable: True
      # 类型，暂支持restart_process与restart_website
      type: restart_process
      name: httpd.exe
    gateway:
      type: nginx
      upstream_port: 9090
      config_file: /etc/nginx/conf.d/www.aaa.com.conf

  - site: test.bbb.com
    max_failed: 7
    timeout: 3
    check_method: post
    post_data:
      key1: value1
      key2: value2
    gateway:
      type: static
      servers:
      - 128.0.100.171:80
      - 128.0.100.178:80

  - site: test.aaa.com
    gateway:
      type: slb
      id: 1100000222
      # 前端监听的端口
      port: 80

gateway:
  nginx:
    user: root
    # 暂不支持密码，未使用pam模块
    # password: password
    hosts:
    # 如果两台是一样，一台就可以，如果多台不一样，取合集
    - 128.0.255.10
    - 128.0.255.11

  slb:
    key: key
    secret: secret
    region: cn-hz

notify:
  - type: dingding
    token: 201ce5cecb1343bbb6d59550efbca1567c2b08ea8843d966f1c76b309308c25b5

  - type: wechat
    secret: secret
    corp_id: asekey
    users:
      - user1
      - user2