sites:
  - site: www.aaa.com
    timeout: 5
    # 一分钟之内最大允许的异常状态次数,达到后会采取动作
    max_failed: 5
    # 最大允许下线的主机，达到该值后，新主机即使异常也不执行任何动作,但会发送通知。
    # 如果该值和服务器数量一样多，就不执行动作，只发送通知
    max_inactive: 1
    # 通过读取NGINX中的配置文件来获取后端Servers，但要求后端端口要一致
    config_file: /etc/nginx/conf.d/www.aaa.com.conf
    backend_port: 80
    # upstream_file与servers同时存在时，优先读取servers里面的值
    servers:
      - 128.0.255.10:9090
      - 128.0.255.10:5000
      - 128.0.255.10:9092
    gateway_type: nginx

  - site: test.bbb.com
    max_failed: 7
    timeout: 5
    max_inactive: 1
    servers:
      - 128.0.255.30:80
    gateway_type: nginx

nginxs:
  - 128.0.255.10
  - 128.0.100.170

notify:
#  wechat:
#    corpid: wechat-corpid
#    secret: wechat-secret
#    users:
#      - tkggvfhpce2
#      - user2

#  email:
#    server: smtp.domain.com
#    username: username
#    password: password
#    users:
#      - username@domain.com
#      - user2@domain.com

 -  type: dingding
    robot_token: 01ce5cecb1343bbb6d59550efbca1567c2b08ea8843d966f1c76b309308c25b5