sites:
  test.aaa.com:
    servers:
    - 192.168.1.10:8080
    gateway_type: nginx

  test.bbb.com:
    servers:
      - 192.168.1.10:8080
    gateway_type: nginx

nginxs:
  - 128.0.255.10
  - 128.0.100.170

notify:
  wechat:
    corpid: wechat-corpid
    secret: wechat-secret
    users:
      - tkggvfhpce2
      - user2

  email:
    server: smtp.domain.com
    username: username
    password: password
    users:
      - username@domain.com
      - user2@domain.com

  dingding:
    robot_token: token